name: SentinelX
version: '${project.version}'
main: pl.syntaxerr.SentinelX
api-version: '1.21'
authors: [SyntaxDevTeam]
description: Cenzor zamieniający niecenzuralne słowa na ocenzurowaną wersję lub całkowicie je usuwający
website: https://github.com/SyntaxDevTeam/SentinelX
