name: SentinelX
version: '1.0-SNAPSHOT'
main: pl.syntaxerr.SentinelX
api-version: '1.21'
authors: [ Syntaxerr ]
description: Cenzor zamieniający niecenzuralne słowa na ocenzurowaną wersję lub całkowicie je usuwający
website: https://github.com/SyntaxDevTeam/SentinelX
commands:
  sentinelx:
    description: Komenda pluginu SentinelX.
  slx:
    description: Komenda pluginu SentinelX.
